version: '3.2'

volumes:
  db-data:

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    ports:
    - "7432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
    - "8080:8080"